inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

RSpec/DescribeClass:
  Exclude:
    - spec/db/**/*
    - spec/lib/tasks/**/*

RSpec/ExampleLength:
  Max: 20
  Exclude:
    - spec/requests/swagger/**/*
    - spec/requests/api/v1/analytics_spec.rb
    - spec/services/analytics_query_spec.rb

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - spec/db/**/*
    - spec/requests/swagger/**/*
    - spec/requests/api/v1/analytics_spec.rb
    - spec/services/analytics_query_spec.rb

RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/swagger/**/*

RSpec/ScatteredSetup:
  Exclude:
    - spec/requests/swagger/**/*

RSpec/EmptyLineAfterFinalLet:
  Exclude:
    - spec/requests/swagger/**/*

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/requests/swagger/**/*

RSpec/InstanceVariable:
  Exclude:
    - spec/requests/swagger/**/*
