inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 2
